package vm

import "github.com/vertexdlt/vertexvm/opcode"

type gasTable [256]uint64

// Cost for generics operations
const (
	GasStack     uint64 = 1
	GasFrame     uint64 = 1
	GasSP        uint64 = 1
	GasJump      uint64 = 3
	GasBlock     uint64 = 5
	GasNumerics1 uint64 = 1
	GasNumerics2 uint64 = 2
	GasMemory    uint64 = 1
)

// Gas is the struct store current state of vm execution
type Gas struct {
	limit uint64
	used  uint64
}

func newGasTable() gasTable {
	return gasTable{
		opcode.Block:             GasFrame + GasBlock,
		opcode.Loop:              GasFrame + GasBlock,
		opcode.If:                GasFrame + GasBlock + GasJump,
		opcode.Else:              GasBlock + GasJump,
		opcode.End:               GasFrame + GasStack + GasStack,
		opcode.Br:                GasFrame + GasJump,
		opcode.BrIf:              GasFrame + GasStack + GasNumerics1 + GasJump,
		opcode.BrTable:           GasStack + GasFrame + GasJump,
		opcode.Return:            GasJump,
		opcode.Call:              GasFrame + GasStack,
		opcode.CallIndirect:      GasFrame + GasFrame + GasStack,
		opcode.Drop:              GasStack,
		opcode.Select:            GasStack + GasStack + GasStack + GasNumerics1 + GasStack,
		opcode.GetLocal:          GasFrame + GasStack + GasStack,
		opcode.SetLocal:          GasFrame + GasStack + GasStack,
		opcode.TeeLocal:          GasFrame + GasStack + GasStack,
		opcode.GetGlobal:         GasFrame + GasStack + GasStack,
		opcode.SetGlobal:         GasFrame + GasStack + GasStack,
		opcode.I32Load:           GasFrame + GasFrame + GasStack + GasMemory,
		opcode.I64Load:           GasFrame + GasFrame + GasStack + GasMemory,
		opcode.F32Load:           GasFrame + GasFrame + GasStack + GasMemory,
		opcode.F64Load:           GasFrame + GasFrame + GasStack + GasMemory,
		opcode.I32Load8S:         GasFrame + GasFrame + GasStack + GasMemory,
		opcode.I32Load8U:         GasFrame + GasFrame + GasStack + GasMemory,
		opcode.I32Load16S:        GasFrame + GasFrame + GasStack + GasMemory,
		opcode.I32Load16U:        GasFrame + GasFrame + GasStack + GasMemory,
		opcode.I64Load8S:         GasFrame + GasFrame + GasStack + GasMemory,
		opcode.I64Load8U:         GasFrame + GasFrame + GasStack + GasMemory,
		opcode.I64Load16S:        GasFrame + GasFrame + GasStack + GasMemory,
		opcode.I64Load16U:        GasFrame + GasFrame + GasStack + GasMemory,
		opcode.I64Load32S:        GasFrame + GasFrame + GasStack + GasMemory,
		opcode.I64Load32U:        GasFrame + GasFrame + GasStack + GasMemory,
		opcode.I32Store:          GasFrame + GasFrame + GasStack + GasMemory,
		opcode.I64Store:          GasFrame + GasFrame + GasStack + GasMemory,
		opcode.F32Store:          GasFrame + GasFrame + GasStack + GasMemory,
		opcode.F64Store:          GasFrame + GasFrame + GasStack + GasMemory,
		opcode.I32Store8:         GasFrame + GasFrame + GasStack + GasMemory,
		opcode.I32Store16:        GasFrame + GasFrame + GasStack + GasMemory,
		opcode.I64Store8:         GasFrame + GasFrame + GasStack + GasMemory,
		opcode.I64Store16:        GasFrame + GasFrame + GasStack + GasMemory,
		opcode.I64Store32:        GasFrame + GasFrame + GasStack + GasMemory,
		opcode.MemorySize:        GasFrame + GasStack,
		opcode.MemoryGrow:        GasFrame + GasStack + GasStack,
		opcode.I32Const:          GasFrame + GasStack,
		opcode.I64Const:          GasFrame + GasStack,
		opcode.F32Const:          GasFrame + GasStack,
		opcode.F64Const:          GasFrame + GasStack,
		opcode.I32Eqz:            GasStack + GasNumerics1 + GasStack,
		opcode.I32Eq:             GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32Ne:             GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32LtS:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32LtU:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32GtS:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32GtU:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32LeS:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32LeU:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32GeS:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32GeU:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64Eqz:            GasStack + GasNumerics1 + GasStack,
		opcode.I64Eq:             GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64Ne:             GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64LtS:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64LtU:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64GtS:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64GtU:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64LeS:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64LeU:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64GeS:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64GeU:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F32Eq:             GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F32Ne:             GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F32Lt:             GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F32Gt:             GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F32Le:             GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F32Ge:             GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F64Eq:             GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F64Ne:             GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F64Lt:             GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F64Gt:             GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F64Le:             GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F64Ge:             GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32Clz:            GasStack + GasNumerics1 + GasStack,
		opcode.I32Ctz:            GasStack + GasNumerics1 + GasStack,
		opcode.I32Popcnt:         GasStack + GasNumerics1 + GasStack,
		opcode.I32Add:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32Sub:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32Mul:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32DivS:           GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32DivU:           GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32RemS:           GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32RemU:           GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32And:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32Or:             GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32Xor:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32Shl:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32ShrS:           GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32ShrU:           GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32Rotl:           GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32Rotr:           GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64Clz:            GasStack + GasNumerics1 + GasStack,
		opcode.I64Ctz:            GasStack + GasNumerics1 + GasStack,
		opcode.I64Popcnt:         GasStack + GasNumerics1 + GasStack,
		opcode.I64Add:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64Sub:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64Mul:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64DivS:           GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64DivU:           GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64RemS:           GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64RemU:           GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64And:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64Or:             GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64Xor:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64Shl:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64ShrS:           GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64ShrU:           GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64Rotl:           GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I64Rotr:           GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F32Abs:            GasStack + GasNumerics1 + GasStack,
		opcode.F32Neg:            GasStack + GasNumerics1 + GasStack,
		opcode.F32Ceil:           GasStack + GasNumerics1 + GasStack,
		opcode.F32Floor:          GasStack + GasNumerics1 + GasStack,
		opcode.F32Trunc:          GasStack + GasNumerics1 + GasStack,
		opcode.F32Nearest:        GasStack + GasNumerics1 + GasStack,
		opcode.F32Sqrt:           GasStack + GasNumerics1 + GasStack,
		opcode.F32Add:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F32Sub:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F32Mul:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F32Div:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F32Min:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F32Max:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F32Copysign:       GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F64Abs:            GasStack + GasNumerics1 + GasStack,
		opcode.F64Neg:            GasStack + GasNumerics1 + GasStack,
		opcode.F64Ceil:           GasStack + GasNumerics1 + GasStack,
		opcode.F64Floor:          GasStack + GasNumerics1 + GasStack,
		opcode.F64Trunc:          GasStack + GasNumerics1 + GasStack,
		opcode.F64Nearest:        GasStack + GasNumerics1 + GasStack,
		opcode.F64Sqrt:           GasStack + GasNumerics1 + GasStack,
		opcode.F64Add:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F64Sub:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F64Mul:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F64Div:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F64Min:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F64Max:            GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.F64Copysign:       GasStack + GasStack + GasNumerics2 + GasStack,
		opcode.I32WrapI64:        GasStack + GasNumerics1 + GasStack,
		opcode.I32TruncSF32:      GasStack + GasNumerics1 + GasStack,
		opcode.I32TruncUF32:      GasStack + GasNumerics1 + GasStack,
		opcode.I32TruncSF64:      GasStack + GasNumerics1 + GasStack,
		opcode.I32TruncUF64:      GasStack + GasNumerics1 + GasStack,
		opcode.I64ExtendSI32:     GasStack + GasNumerics1 + GasStack,
		opcode.I64ExtendUI32:     GasStack + GasNumerics1 + GasStack,
		opcode.I64TruncSF32:      GasStack + GasNumerics1 + GasStack,
		opcode.I64TruncUF32:      GasStack + GasNumerics1 + GasStack,
		opcode.I64TruncSF64:      GasStack + GasNumerics1 + GasStack,
		opcode.I64TruncUF64:      GasStack + GasNumerics1 + GasStack,
		opcode.F32ConvertSI32:    GasStack + GasNumerics1 + GasStack,
		opcode.F32ConvertUI32:    GasStack + GasNumerics1 + GasStack,
		opcode.F32ConvertSI64:    GasStack + GasNumerics1 + GasStack,
		opcode.F32ConvertUI64:    GasStack + GasNumerics1 + GasStack,
		opcode.F32DemoteF64:      GasStack + GasNumerics1 + GasStack,
		opcode.F64ConvertSI32:    GasStack + GasNumerics1 + GasStack,
		opcode.F64ConvertUI32:    GasStack + GasNumerics1 + GasStack,
		opcode.F64ConvertSI64:    GasStack + GasNumerics1 + GasStack,
		opcode.F64ConvertUI64:    GasStack + GasNumerics1 + GasStack,
		opcode.F64PromoteF32:     GasStack + GasNumerics1 + GasStack,
		opcode.I32ReinterpretF32: GasStack + GasNumerics1 + GasStack,
		opcode.I64ReinterpretF64: GasStack + GasNumerics1 + GasStack,
		opcode.F32ReinterpretI32: GasStack + GasNumerics1 + GasStack,
		opcode.F64ReinterpretI64: GasStack + GasNumerics1 + GasStack,
	}
}

var gasTableAlpha = newGasTable()

// GetGasCost calculates op cost
func GetGasCost(op opcode.Opcode) uint64 {
	return gasTableAlpha[op]
}
